---
description: "Process the Watcher prompt queue (EAT-QUEUE). Default handler is agents/queue.mdc via dispatcher; this file is kept for rollback — when routing points here, run the full flow below."
globs: []
alwaysApply: false
---

# Auto EAT-QUEUE (context rule)

- **Default routing**: EAT-QUEUE / Process queue / EAT-CACHE are routed by [always/dispatcher.mdc](.cursor/rules/always/dispatcher.mdc) to the **Queue/Dispatcher subagent** [agents/queue.mdc](.cursor/rules/agents/queue.mdc). When that rule is active, run Part A (Prompt-queue flow) there.
- **When this file is the active handler** (e.g. after rollback): Run the full queue processor flow below (Step 0 → steps 1–8). Rollback = point system-funnels (and dispatcher) back to `context/auto-eat-queue.mdc` for EAT-QUEUE.
- **Reference**: [Cursor-Skill-Pipelines-Reference](3-Resources/Second-Brain/Cursor-Skill-Pipelines-Reference.md). **MCP safety**: [mcp-obsidian-integration.mdc](.cursor/rules/always/mcp-obsidian-integration.mdc). Laptop-only queue (mobile = observe + fill Ingest only).

## How to activate

When the instruction contains **EAT-QUEUE**, **Process queue**, **EAT-CACHE**, or **eat cache** and **this rule** is the active handler, run the queue processor flow below. If the user pasted YAML with `mode: EAT-CACHE` and `queued_prompts`, use that as the queue source in step 1.

**Optional pre-dispatch (approved proposals and Decision Wrappers — canonical ingest apply path)**: Before or after reading the queue, you may still scan for **Decision Wrappers under `Ingest/Decisions/**`** (e.g. `Ingest-Decisions/`) with `decision_candidate: true` and `approved: true` (and, optionally, `user_guidance` or `#guidance-aware`). For each such wrapper, you MAY inject a queue entry into the in-memory queue (do not write to prompt-queue.jsonl) with `mode: "INGEST_MODE"`, `source_file` set to the wrapper path, and `prompt` populated from the wrapper’s `user_guidance` / “Thoughts” block; however, the **primary, persistent driver** for wrapper consumption is now the `CHECK_WRAPPERS` queue entry described below. This injected entry is still a valid route for applying ingest moves/renames, but no `obsidian_move_note` / `obsidian_rename_note` for Ingest notes should run unless it ultimately comes from an approved Decision Wrapper via either this mechanism or the `CHECK_WRAPPERS` entry. You may also scan for other notes with `approved: true` and a matching proposal id/tag to inject non-ingest entries (e.g. for organize/archive proposals). **Safety:** Only inject if the original file still exists at the path (wrapper or source note) and is **not excluded** (e.g. not under Backups/, not watcher-protected). Prevents ghost injections. Document in Queue-Sources and Templates (re-queue after edit).

### Wrapper-check requeue semantics (`CHECK_WRAPPERS` entry)

- **Purpose**: Ensure that approved Decision Wrappers are always processed **first** whenever EAT-QUEUE runs, and that wrapper checks are re-queued until all approved wrappers have been applied.
- **Queue entry shape**: A wrapper-check entry is a line in `.technical/prompt-queue.jsonl` with at least:  
  `{"mode":"INGEST MODE","prompt":"CHECK_WRAPPERS","source_file":"Ingest/Decisions/","id":"check-wrappers-<timestamp>"}`  
  Other fields (e.g. `commander_source`) are optional. Ingest Phase 1 (see para-zettel-autopilot) is responsible for **ensuring at least one such entry exists** whenever a new Decision Wrapper is created and none is present.
- **Ordering**: During step 4 (Ordering), treat any entry whose `mode` is `INGEST_MODE` and whose `prompt` starts with or equals `"CHECK_WRAPPERS"` as a **meta-entry that must be processed before all other modes**, including other INGEST_MODE entries. When sorting, pin these entries to the front of the queue (stable among themselves by timestamp), then apply the canonical pipeline order to the remaining entries.
- **Processed-wrapper archive**: After a wrapper is applied, it is moved to **`4-Archives/Ingest-Decisions/`** (with subfolders mirroring the live structure, e.g. `4-Archives/Ingest-Decisions/Ingest-Decisions/`) so `Ingest/Decisions/**` stays uncluttered. Wrappers are kept for training/history and are never auto-deleted. Step 0 only enumerates notes under `Ingest/Decisions/` (not the archive), so moved wrappers are no longer scanned.
- **Execution semantics**:
  - When dispatching a `CHECK_WRAPPERS` entry:
    1. **Scan wrappers**: Enumerate all markdown notes under `Ingest/Decisions/` (including subfolders such as `Ingest-Decisions/`). For each wrapper:
       - Skip if `approved: false` or explicitly marked `processed: true` (or equivalent flag such as `used_at` already set by a prior apply run).
       - If `approved: true` and not processed:
         - Use `feedback-incorporate` to resolve `approved_option` / `approved_path` into `hard_target_path` plus `guidance_text`.
         - Run an **apply-mode INGEST** pipeline for the original Ingest note (see para-zettel-autopilot “Apply-mode ingest”) using `hard_target_path` and guidance; this run may perform `obsidian_move_note` / `obsidian_rename_note` subject to confidence + snapshot gates.
         - Update the wrapper (e.g. set `used_at` and/or `processed: true`) and log in Ingest-Log that the decision was applied.
         - **Move the wrapper to the archive**: Derive archive path from the wrapper's current path: replace prefix `Ingest/Decisions/` with `4-Archives/Ingest-Decisions/` (e.g. `Ingest/Decisions/Refinements/Decision-for-x.md` → `4-Archives/Ingest-Decisions/Refinements/Decision-for-x.md`). Call `obsidian_ensure_structure` with `folder_path` set to the parent directory of that archive path. Create a per-change snapshot of the wrapper note (obsidian-snapshot skill). Then call `obsidian_move_note`(wrapper_path, derived_archive_path) with `dry_run: true`, review effects, then `dry_run: false` to commit. This keeps `Ingest/Decisions/**` for pending wrappers only; subfolders (Ingest-Decisions, Roadmap-Decisions, Refinements, Low-Confidence, Errors) are mirrored under 4-Archives/Ingest-Decisions/.
  - **Internal note placement and idempotency** (when adding a Wrapper state block for orphan/true-orphan wrappers): Before inserting the `## Wrapper state` block (or equivalent reserved callout), the agent must **skip appending** if (1) frontmatter already contains tag `#orphan` or `#true-orphan` (or `tags` array includes `orphan` / `true-orphan`), or (2) the note body already contains the section header `## Wrapper state` (or the reserved callout title used for the internal note). If either check fails, do not append; prevents duplicate notes on repeated EAT-QUEUE runs.
  - **Orphan tag definitions**: **#orphan** = companion (original note) is missing from expected path but still somewhere in the vault (found at P ≠ target_path). **#true-orphan** = companion is missing from expected path and from entire vault (search negative).
  - **Vault search implementation** (when resolving companion location for stale/orphan wrappers): Companion search is not magic — use an explicit call. **Primary:** Call **`obsidian_global_search`** with a query derived from the original note (e.g. filename or title from `original_path` basename). Filter results to the vault; exclude the wrapper path. Treat a single path match as "found at P"; multiple candidates may be listed in the trace. **Fallback:** If global search is unavailable or returns nothing, use **`obsidian_list_notes`** (or equivalent) and filter by **basename** of `original_path` (and optionally by note title from the wrapper). Document in the rule for future readers: "Companion search: `obsidian_global_search` with query from original_path basename (and optionally title); fallback: list_notes + basename filter." If found at P and P equals resolved `target_path` → original at target (archive wrapper). If found at P ≠ target_path → Orphan (#orphan); if not found → True Orphan (#true-orphan).
  - **CHECK_WRAPPERS Ingest-Log format**: All CHECK_WRAPPERS-related lines in Ingest-Log must follow the existing format `timestamp | Excerpt | PARA | Changes | Confidence | Proposed MV | Flag` and be **prefixed with** `CHECK_WRAPPERS: ` for greppability (e.g. `grep "CHECK_WRAPPERS:" 3-Resources/Ingest-Log.md`). Examples: apply/retry — `CHECK_WRAPPERS: <timestamp> | Retry apply (stale; original still in Ingest): <original_path> | Resource | <changes> | <conf>% | <proposed_mv or target_path> | `; stale archived — `CHECK_WRAPPERS: <timestamp> | Stale wrapper archived; original at target | ... | ... | ... | 4-Archives/Ingest-Decisions/<basename>.md | `; orphan — `CHECK_WRAPPERS: <timestamp> | Orphan; companion at P, expected at target_path | ... | ... | | | #orphan`; true orphan — `CHECK_WRAPPERS: <timestamp> | True Orphan; companion not found in vault | ... | ... | | | #true-orphan`.
    2. **Determine requeue**:
       - After scanning all wrappers, check whether **any wrappers remain** with `decision_candidate: true`, `approved: true`, and **not** marked processed.
       - If such wrappers remain, ensure that **a fresh `CHECK_WRAPPERS` entry** exists in the queue that will be written back at step 8 (Clear passed entries). This can reuse the same `source_file` (`"Ingest/Decisions/"`) and a new `id`.
       - If no unprocessed, approved wrappers remain, do **not** re-add the `CHECK_WRAPPERS` entry; wrapper checking will resume automatically when ingest creates a new wrapper and para-zettel-autopilot appends a new `CHECK_WRAPPERS` line.
  - Treat the current `CHECK_WRAPPERS` entry itself as **successful** once this scan-and-apply cycle completes; it should be removed from the queue on this run and only re-inserted when needed as above.

### Always-check wrappers (Option A — reliability)

- **Runs first, every EAT-QUEUE run**, before reading the queue. No dependency on the queue file containing a `CHECK_WRAPPERS` entry; approved wrappers are never stuck.
- **Step 0 (always-run)**:
  1. Enumerate all markdown notes under `Ingest/Decisions/` **recursively** (including subfolders such as `Ingest-Decisions/`). If this folder tree is missing or empty, proceed to step 1 (Read queue) with no further action.
  2. For each wrapper, read frontmatter. Skip if `approved: false` **and** `re-wrap` is not true **and** `re-try` is not true (so wrappers with `re-wrap: true` or `re-try: true` are always considered).
  3. **Branch A — approved, re-wrap, or re-try, not processed:** For each wrapper with (`approved: true` **or** `re-wrap: true` **or** `re-try: true`) and neither `processed: true` nor `used_at` set:
     - Read wrapper frontmatter (at least `wrapper_type`, `approved_option`, `approved_path`, `original_path`, `re-wrap`, `re-try`, `re_try_count`, `phase_path`, `pipeline`, `suggested_project_name` when present).
     - Use `feedback-incorporate` to resolve `approved_option` / `approved_path` into `hard_target_path` and `guidance_text`. Treat `re-wrap: true` or `approved_option: 0` as re-wrap intent (no `hard_target_path`). For `wrapper_type: error`, recovery may be driven by `approved_option` alone (e.g. "Force backup then retry") without a path.
     - **Re-try branch (re-try: true or approved_option: R, and not re-wrap):** When the user requested re-queue with guidance (roadmap/phase-direction wrappers): (1) **Cap check:** Read `re_try_max_loops` from Second-Brain-Config (default 3). If wrapper has `re_try_count` >= re_try_max_loops, **abort** re-try: log `#review-needed` to Feedback-Log.md per Error Handling Protocol; **create a cap-hit wrapper** under `Ingest/Decisions/Roadmap-Decisions/` with options per [User-Questions-and-Options-Reference](3-Resources/Second-Brain/User-Questions-and-Options-Reference.md) §3: A = Force approve, B = Prune branch, 0 = Re-wrap full phase (pad to 7 per MCP-Tools); do **not** append queue entry. (2) **Else:** Resolve guidance from wrapper (Thoughts block → `guidance_text`; optional `user_guidance` frontmatter). **Session continuity:** When building the queue entry, inject into `params`: **session_success_hint** (last 1–3 lines from Watcher-Result.md where status: success; read via obsidian_read_note); **git_diff_hint** (when vault has `.git`, use code_execution to run `git diff --summary` (read-only); if no .git or command fails, fallback to obsidian_list_notes on Versions/ or log fallback to Errors.md); **previous_decisions** (array of short strings from recent approved wrappers, cap 5–10); **re_try_count**: (wrapper.re_try_count || 0) + 1. Append **one entry** to `.technical/prompt-queue.jsonl` with `mode` (EXPAND-ROAD or TASK-TO-PLAN-PROMPT from wrapper context), `source_file` (original_path or phase_path), `prompt` (guidance_text), `id`, `params`. Set wrapper `processed: true` and `used_at`; **move wrapper to archive** at `4-Archives/Ingest-Decisions/Roadmap-Decisions/` (ensure_structure, per-change snapshot, move with dry_run then commit). Log to Ingest-Log: `CHECK_WRAPPERS: <timestamp> | Re-try: <original_path> → queued <mode> with guidance; wrapper archived.`
     - **Re-wrap branch (re-wrap: true or approved_option: 0 or no hard_target_path), when not re-try:** When the user is unhappy with options and requested re-wrap (or chose "reject all"):
       - Pull seed from wrapper: "Thoughts / corrections / why this location?" block → `guidance_text`; keep `original_path`, optional `previous_choice` (previous `approved_option` + path for traceability). Create backup (obsidian_create_backup) for the wrapper path. Create per-change snapshot of the wrapper (obsidian-snapshot skill). Call `obsidian_ensure_structure`(folder_path: `4-Archives/Ingest-Decisions/Re-Wrap/Ingest-Decisions`). Move current wrapper to `4-Archives/Ingest-Decisions/Re-Wrap/Ingest-Decisions/<basename>.md` via `obsidian_move_note`(wrapper_path, new_path) with `dry_run: true` then `dry_run: false`. Create a **new** Decision Wrapper under `Ingest/Decisions/Ingest-Decisions/` for the same `original_path` using the same template and creation logic as para-zettel-autopilot (e.g. call `propose_para_paths` in wrapper mode to get A–G candidates, fill `Templates/Decision-Wrapper.md`). Set on the new wrapper: `approved: false`; do **not** set `approved_option` or `approved_path`. Add in the new wrapper body a line linking to the archived wrapper, e.g. `Archived previous: [[4-Archives/Ingest-Decisions/Re-Wrap/Ingest-Decisions/<basename>.md]]`. Optionally set `previous_choice` in frontmatter (previous option + path). Log to Ingest-Log: `CHECK_WRAPPERS: <timestamp> | Re-wrapping <original_path> → archived <archived_path>; new wrapper at <new_wrapper_path> | ... | ... | ... | `.
     - **Path-apply (when hard_target_path is present):** Branch by `wrapper_type` and `pipeline` (apply-from-wrapper semantics; see Cursor-Skill-Pipelines-Reference and Vault-Layout). **ingest-decision / roadmap-decision / force-wrapper with original_path under Ingest/**: Run **apply-mode INGEST** for the original note (para-zettel-autopilot "Apply-mode ingest"): backup/snapshot gates and `obsidian_move_note` (dry_run then commit) / `obsidian_rename_note` using `hard_target_path`. **phase-direction**: Apply per Cursor-Skill-Pipelines-Reference § Apply-from-wrapper: per-change snapshot of target roadmap/phase note (`phase_path` or `original_path`) → append provenance callout (`> [!provenance] Evolved from [[Master-Goal]] via [[Wrapper-1]] (re-try on <date>) → [[Wrapper-2]] (approved).`) and, near the approved task bullet, inline callout with "Comment guidance: …" (see plan §6.2) → set `processed: true`, `used_at` on wrapper → move wrapper to `4-Archives/Ingest-Decisions/Roadmap-Decisions/`. **handoff-readiness**: Apply per Cursor-Skill-Pipelines-Reference § Apply-from-wrapper: per-change snapshot of target phase note (`phase_path` or `original_path`) → apply chosen option (append pseudo-code stub, append resolution, or re-queue with guidance); set `processed: true`, `used_at`; move wrapper to `4-Archives/Ingest-Decisions/Roadmap-Decisions/`. If "Accept as-is", set frontmatter flag on phase to skip hand-off gate on next run. **mid-band-refinement or force-wrapper with pipeline: organize**: Run apply for organize — backup/snapshot for `original_path`, then `obsidian_ensure_structure`(folder_path: parent of hard_target_path), then `obsidian_move_note`(original_path, hard_target_path) with dry_run then commit; optional rename per name-enhance. **pipeline: archive**: Same pattern — move note at `original_path` to `hard_target_path` (under 4-Archives/…) after backup/snapshot and ensure_structure. **pipeline: distill / express**: Call **distill-apply-from-wrapper** or **express-apply-from-wrapper** skill (reads wrapper frontmatter, re-runs autonomous-distill or autonomous-express with approved_option as distill_lens / express_view override). **low-confidence**: When `wrapper_type: low-confidence` and `approved: true`, interpret `approved_option`: A–C → apply path (move note to chosen candidate path); D → queue SEEDED-ENHANCE or add DISTILL LENS entry; E → run highlight-seed-enhance on original; F → tag/move wrapper or note to review-pending; G → no-op, archive wrapper. Then move wrapper to archive (derive path from current path as above). **error**: When `wrapper_type: error` and `approved: true`, execute the chosen recovery from `approved_option` / `approved_path`: e.g. run `obsidian_ensure_backup` then re-queue the same pipeline for `original_path`; or apply move to alternative path; or skip and archive wrapper only. Then move wrapper to archive (derive path from current path).
     - In all cases, after a successful apply:
       - Update the wrapper (e.g. set `used_at`, `processed: true`) and log to Ingest-Log.md.
       - **Move the wrapper to the archive**: Derive archive path from the wrapper's current path: replace prefix `Ingest/Decisions/` with `4-Archives/Ingest-Decisions/` (e.g. `Ingest/Decisions/Ingest-Decisions/Decision-for-x.md` → `4-Archives/Ingest-Decisions/Ingest-Decisions/Decision-for-x.md`). Call `obsidian_ensure_structure` with `folder_path` set to the parent directory of that archive path. Create a per-change snapshot of the wrapper note (obsidian-snapshot skill). Then `obsidian_move_note`(wrapper_path, derived_archive_path) with `dry_run: true` then `dry_run: false`. Processed wrappers are kept in `4-Archives/Ingest-Decisions/` (with subfolders mirrored) for training/history and never auto-deleted; `Ingest/Decisions/` stays for pending only.
  4. **Branch B — approved and processed but still in Decisions (location check required):** For each wrapper with `approved: true` and (`processed: true` or `used_at` set) and whose path is under `Ingest/Decisions/` (i.e. not already under `4-Archives/Ingest-Decisions/`), the agent **must** run a location check — do not skip. Resolve `target_path` from the wrapper (`approved_option` / `approved_path`). Run companion search: **primary** `obsidian_global_search` with query from `original_path` basename (and optionally title); **fallback** `obsidian_list_notes` + filter by basename; exclude the wrapper path. Then:
     - **If companion found at P and P equals `target_path`:** Treat as "original at target". Archive the wrapper: derive archive path by replacing prefix `Ingest/Decisions/` with `4-Archives/Ingest-Decisions/` on the wrapper path; call `obsidian_ensure_structure`(folder_path: parent of that path), per-change snapshot of wrapper (obsidian-snapshot skill), then `obsidian_move_note`(wrapper_path, derived_archive_path) with `dry_run: true` then `dry_run: false`. Log CHECK_WRAPPERS: "Stale wrapper archived; original at target" with the derived archive path.
     - **If companion found at P and P ≠ `target_path`:** Tag wrapper **#orphan** (missing from expected path but still in vault). Add `## Wrapper state` block (or equivalent reserved callout) only if not already present per idempotency (see "Internal note placement and idempotency" above). Log CHECK_WRAPPERS line with `#orphan`. Optionally move wrapper to `4-Archives/Ingest-Decisions/` with tag so Decisions stays clean.
     - **If companion not found (search negative):** Tag wrapper **#true-orphan** (missing from expected path and from entire vault). Add `## Wrapper state` block only if not already present per idempotency. Log CHECK_WRAPPERS line with `#true-orphan`. Optionally move wrapper to `4-Archives/Ingest-Decisions/` with tag.
  5. After the scan, determine **approved_wrappers_remaining**: re-enumerate `Ingest/Decisions/*.md` and set to true if any note has `decision_candidate: true`, `approved: true`, and is **not** marked processed (and has no `used_at`). This flag is used at step 8.
  6. Optionally append one line to Watcher-Result.md for this step, e.g. `requestId: check-wrappers-always | status: success | message: "Scanned N wrappers; applied M." | trace: "" | completed: <ISO8601>`.
  7. Proceed to step 1 (Read queue). Do **not** exit or skip the rest of the flow based on queue contents until after step 2.
- **When a `CHECK_WRAPPERS` entry appears in the queue** (steps 6–7): Do **not** run the wrapper execution semantics again; they were already run in step 0. Treat the entry as **successful** and remove it at step 8 (no double-apply).
- **Step 8 (Clear passed entries)**: When rewriting `.technical/prompt-queue.jsonl`, if **approved_wrappers_remaining** is true, **include one `CHECK_WRAPPERS` entry** (e.g. `{"mode":"INGEST MODE","prompt":"CHECK_WRAPPERS","source_file":"Ingest/Decisions/","id":"check-wrappers-<timestamp>"}`) in the set of lines written, so the next run has it for visibility and the always-check in step 0 will process any remaining approved wrappers.

## Queue processor flow

### 0. Always-check wrappers (runs first)

- Run the **Always-check wrappers** logic above (enumerate `Ingest/Decisions/`, Branch A: apply approved unprocessed wrappers, Branch B: location check and archive or tag #orphan/#true-orphan for processed wrappers still in Decisions, set **approved_wrappers_remaining**). Then continue to step 1.

### 1. Read queue

- **From file**: Read **`.technical/prompt-queue.jsonl`** from the workspace (this rollback handler uses the legacy single-file path; the default Queue/Dispatcher resolves **PQ** per [[.cursor/rules/agents/queue.mdc|queue.mdc]] **A.0x**). If the file is **missing, unreadable, or empty**, treat as **empty queue input** and **continue to §2 Parse and validate** — do **not** exit early for prompt-queue flows. Empty input is **not** a terminal condition by itself; it must reach **§2** so zero valid entries can invoke **A.1b** when Second-Brain-Config **`queue_continuation.empty_queue_bootstrap_enabled`** is **true**, matching [[3-Resources/Second-Brain/Queue-Sources|Queue-Sources]] (no early exit on empty PQ) and **queue.mdc** **A.1**. **True terminal “nothing to process”** (optional Watcher-Result line only; no pipeline dispatch) is allowed **only** when, after **§2** parse, there are **zero valid entries** **and** **`empty_queue_bootstrap_enabled`** is **not** **`true`** (same gate as the first bullet under §2 zero-valid branch).
- **From pasted payload**: If the user pasted YAML with `mode: EAT-CACHE` and `queued_prompts`, parse `queued_prompts` (array of objects with `id`, `timestamp`, `mode`, `prompt`, `source_file`). If missing or not an array, treat as empty and exit. If pasted content is not valid YAML, treat as empty and optionally reply that the payload could not be parsed.

### 2. Parse and validate (§2d)

- Parse the queue line-by-line (or use the parsed `queued_prompts`). For each line, try `JSON.parse(line)`. If parse fails, skip that line and count skipped (invalid) lines.
- Require each object to have at least `mode` (string). If missing or not a string, treat as invalid: skip and count.
- **Filter out past failures (§2e)**: Remove any entry where `queue_failed === true` (or `tags` includes `"queue-failed"`). Do not process these; optionally log how many were skipped as past failures.
- If after parsing and filtering there are **zero valid entries**, run the same **A.1b empty-queue continuation bootstrap** contract as [agents/queue.mdc](.cursor/rules/agents/queue.mdc) before exiting:
  - Check `queue_continuation.empty_queue_bootstrap_enabled` in Second-Brain-Config; if not true, exit as empty.
  - Read `.technical/queue-continuation.jsonl` and select the newest eligible continuation record (same gating as A.1b in `agents/queue.mdc`: eligibility, suppress_reason, age window, idempotency key).
  - Build candidate via PromptCraft (`empty_queue_bootstrap_prompt_craft`) or deterministic fallback; if `empty_queue_bootstrap_auto_append` true, append one line to `.technical/prompt-queue.jsonl` and append Watcher-Result `empty-bootstrap-*`.
  - After any successful append, **re-read** `.technical/prompt-queue.jsonl` and **re-parse step 2 once**. If still zero valid entries, exit gracefully.
  - Keep behavior deterministic: at most one bootstrap attempt per EAT-QUEUE run.
- **Fast-path for single entry**: If **valid entry count === 1**, skip steps 3 and 4 (dedup, sort) and go directly to step 5 (Dispatch).

### 3. Clean-up (dedup §2b)

- Deduplicate: same `(mode, prompt, source_file)` → keep first occurrence (by timestamp), drop later. Log collapsed count (e.g. "2 duplicate INGEST entries collapsed into 1").
- Do **not** drop entries that share the same `source_file` but have different modes (e.g. INGEST_MODE + TASK_ROADMAP for the same file); keep both and rely on ordering.
- **Queue-cleanup (slot after dedup)**: When `auto_cleanup_after_process: true` in Second-Brain-Config, after step 8 (Clear passed entries) run the **queue-cleanup** skill (see `.cursor/skills/queue-cleanup/SKILL.md`): mark failed/skipped entries `queue_failed: true`, append short summary to `3-Resources/Errors.md`.

### 4. Ordering (safety §2c)

- **Canonical pipeline order**: (after pulling any `CHECK_WRAPPERS` meta-entries to the front as described above) INGEST_MODE (1) → FORCE_WRAPPER (2) → ORGANIZE_MODE (3) → TASK_ROADMAP (4) → **RESEARCH_AGENT** (4b) → **NORMALIZE_MASTER_GOAL** (5) → **EXPAND_ROAD** (6) → **TASK_TO_PLAN_PROMPT** (7) → **ROADMAP_MODE** (7a) → **RESUME_ROADMAP** (8) → **RESUME-FROM-LAST-SAFE** (8b) → **ROADMAP_ONE_SHOT** (8c; deprecated) → **RECAL-ROAD** (9) → **SYNC-PHASE-OUTPUTS** (10) → **REVERT-PHASE** (11) → **HANDOFF-AUDIT** (11b) → **ROADMAP_HANDOFF_VALIDATE** (11c) → DISTILL_MODE (12) → EXPRESS_MODE (13) → **SCOPING_MODE** (14; alias: DISTILL then EXPRESS on same note) → ARCHIVE_MODE (15) → **AUDIT_CONTEXT** (15b) → TASK_COMPLETE (16) → ADD_ROADMAP_ITEM (17) → SEEDED_ENHANCE (18) → BATCH_DISTILL (19) → BATCH_EXPRESS (20) → ASYNC_LOOP (21) → **NAME_REVIEW** (22) → **GARDEN_REVIEW** (23) → **CURATE_CLUSTER** (24). Sort all remaining entries by this order. Re-queued re-try entries run after TASK_ROADMAP; EXPAND_ROAD before TASK_TO_PLAN_PROMPT per Queue-Sources.
- **Repair-first sub-sort (tiered blocks):** After canonical order, for each **`project_id`**, secondary-sort **`RESUME_ROADMAP`** / **`ROADMAP_MODE`** / **`RESUME_ROADMAP-*`** chain primaries so entries with **`queue_priority: "repair"`** or **`validator_repair_followup: true`** dispatch **before** deepen/advance lines for that project. Same contract as [agents/queue.mdc](.cursor/rules/agents/queue.mdc) **A.4** and Queue-Sources § **Tiered validator queue fields**.
- **Post–little-val tiered branch:** When this file is the active handler, after each successful pipeline run with `little_val_ok` and `validator_context`, apply the same **post–little-val Validator Task → A.5b** rules as **queue.mdc** (hard-block detection, optional repair append, re-sort remainder, **A.7** consumption). **No queue-level IRA.**
- **Chains:** If a **dependency** in a chain fails, abort remaining segments for that `chain_id`. If deps succeed and **primary** hits post–little-val hard block, append repair per tiered spec and **consume** chain entry id when repair append succeeds (see Queue-Sources § Tiered validator queue fields).
- **Overlap detection**: When processing BATCH-DISTILL or BATCH-EXPRESS, merge similar entries (e.g. same mode + >80% path overlap) into one batch; log merge count in Feedback-Log.md.
- **Cap previews**: When emitting async previews (mid-band), cap the number of preview entries at **async_preview_threshold** (from Second-Brain-Config depths or config) to avoid mobile overload; document in Queue-Sources.
- For entries that share the same `source_file`, process them in this same order so that upstream pipelines (e.g. INGEST) run before downstream (e.g. DISTILL). Do not run DISTILL/EXPRESS/ARCHIVE on a path under `Ingest/` until batch INGEST has been run (sorting ensures INGEST is processed first).

### 4b. Decisions preflight (rollback parity)

- **When:** Immediately **after** step **4** (ordering + roadmap per-project dispatchability map per [agents/queue.mdc](.cursor/rules/agents/queue.mdc) **A.4**) and **before** step **5** (Dispatch). When the fast-path skipped step **4** (**valid entry count === 1**), still run preflight for a single **`ROADMAP_MODE`** / **`RESUME_ROADMAP`** / **`RESUME_ROADMAP-*`** line with resolvable **`project_id`** per **queue.mdc** **A.4b** fast-path bullet.
- **Behavior:** Same as **agents/queue.mdc** **A.4b**: gate on **`queue.decisions_preflight`** in Second-Brain-Config; when **`enabled`** is **true** and **`on_drift`** is not **`off`**, run read-only **`.cursor/skills/decisions-preflight/SKILL.md`** once per dispatchable **`project_id`**; cache result; optional **Watcher-Result** when **`watcher_result_on_stale`** and **`stale_surfaces`** non-empty; merge **`## handoff_addendum.decisions_preflight`** (fenced **yaml**) into **`Task(roadmap)`** hand-offs when merging is on. See [[3-Resources/Second-Brain/Docs/Decisions-Log-Operator-Pick-Convention|Decisions-Log-Operator-Pick-Convention]] and Parameters § **Queue decisions preflight**.

### 5. Dispatch (with §2d checks)

- Before running a pipeline for an entry:
  - **CHECK_WRAPPERS no-op**: If the entry has `mode: "INGEST_MODE"` and `prompt` starting with or equal to `"CHECK_WRAPPERS"`, do **not** run the wrapper execution semantics again (already done in step 0). Treat as **success** and append to Watcher-Result; continue to the next entry.
  - If the entry has non-empty `source_file`, verify the file exists in the vault (e.g. `obsidian_read_note` or list notes). If the file is missing, skip this entry; append to Watcher-Result: `requestId: <id> | status: failure | message: "source_file not found: <path>" | trace: "" | completed: <ISO8601>`. Continue to the next entry.
  - If the mode (after normalization) is not in the known list (INGEST_MODE, ORGANIZE_MODE, DISTILL_MODE, EXPRESS_MODE, ARCHIVE_MODE, FORCE_WRAPPER, TASK_ROADMAP, **ROADMAP_MODE**, **RESEARCH_AGENT**, **NORMALIZE_MASTER_GOAL**, **EXPAND_ROAD**, **TASK_TO_PLAN_PROMPT**, **RESUME_ROADMAP**, **RESUME-FROM-LAST-SAFE**, **ROADMAP_ONE_SHOT**, **RECAL-ROAD**, **SYNC-PHASE-OUTPUTS**, **REVERT-PHASE**, **HANDOFF-AUDIT**, **ROADMAP_HANDOFF_VALIDATE**, TASK_COMPLETE, ADD_ROADMAP_ITEM, SEEDED_ENHANCE, BATCH_DISTILL, BATCH_EXPRESS, ASYNC_LOOP, NAME_REVIEW, SCOPING_MODE, SCOPING, **GARDEN_REVIEW**, **CURATE_CLUSTER**, **AUDIT_CONTEXT**) **and** is not a valid **chain mode** (format PRIMARY-DEP1-DEP2-... per Queue-Sources § Chain modes; first segment allowed primary, remaining segments allowed dependency shorthands e.g. RESEARCH, INGEST), skip this entry; append to Watcher-Result: `requestId: <id> | status: failure | message: "unknown or invalid mode: <mode>" | trace: "" | completed: <ISO8601>`. Continue to the next entry. When this rule is the active handler, chain-mode dispatch follows queue.mdc A.5 (parse segments, run deps in order, then primary with collected results).
  - **Params (queue entry `params`)**: When an entry has `params`, merge per fallback chain: 1. Queue entry params 2. user_guidance frontmatter (merge) 3. Config prompt_defaults/profiles (from Second-Brain-Config) 4. MCP tool defaults. **For RESUME_ROADMAP and ROADMAP_MODE, queue entry params override Config `prompt_defaults.roadmap` for every key present on the entry; config is used only for missing keys.** **Validate** merged params (entry + Config + defaults), not only raw entry keys, against MCP-Tools.md contracts before dispatch (e.g. rationale_style in ['concise','detailed','bullet','technical']; context_mode and max_candidates within allowed ranges). If invalid, **reject** the entry: skip dispatch, append to `3-Resources/Errors.md` per Error Handling Protocol, append failure to Watcher-Result, continue to the next entry. If valid, pass the merged params into the pipeline context so that classify_para, propose_para_paths, subfolder_organize (and other MCP-invoking steps) receive them. For roadmap-specific context-utilization tracking, **auto-roadmap** applies an additional default-on rule to `enable_context_tracking` after this generic merge; see the auto-roadmap rule and Parameters for details.
  - **Tech-level injection (roadmap_tech_progression)**: When **Second-Brain-Config** has `roadmap_tech_progression: true` and the entry is **INGEST_MODE** with `source_file` pointing to a note (e.g. under `Ingest/` or `Ingest/Agent-Output/`), read the note or infer from path/frontmatter a **phase number** (e.g. from path segment "Phase-1", "Phase-2", or frontmatter `roadmap-level` / phase). If phase can be inferred: inject into **params** (or merge into existing params) **tech_level**: `high-concept` (phase 1–2), `mid-tech` (phase 3–4), or `pseudo-code` (phase 5+). If phase cannot be inferred, leave tech_level unset. The ingest pipeline (para-zettel-autopilot) uses tech_level for the Cursor-agent direct-move branch (tech_level > 1 + mid-band → no direct move; refinement loop). Document in Queue-Sources § prompt-queue contract.
  - **Roadmap mode normalization (funnel)**: Before matching mode to pipeline, **rewrite** the entry in-memory when `mode` is one of: **RECAL-ROAD**, **REVERT-PHASE**, **SYNC-PHASE-OUTPUTS**, **HANDOFF-AUDIT**, **RESUME-FROM-LAST-SAFE**, **EXPAND-ROAD**. Set `mode: "RESUME_ROADMAP"` and set or merge **params** so that: RECAL-ROAD → `params: { action: "recal" }` (merge with existing params); REVERT-PHASE → `params: { action: "revert-phase", phase: <from payload or params> }`; SYNC-PHASE-OUTPUTS → `params: { action: "sync-outputs" }`; HANDOFF-AUDIT → `params: { action: "handoff-audit", phase_number?: <optional> }`; RESUME-FROM-LAST-SAFE → `params: { action: "resume-from-last-safe" }`; EXPAND-ROAD → `params: { action: "expand", sectionOrTaskLocator: <from payload>, userText: <from prompt> }`. Preserve `source_file`, `id`, and other fields; only change mode and params. Then the **single** roadmap continuation path is RESUME_ROADMAP → auto-roadmap with merged params.
  - **RESUME-ROADMAP + approved roadmap-next-step wrapper (pre-dispatch):** When the entry **mode** is **RESUME_ROADMAP**, **before** invoking auto-roadmap: Resolve **project_id** from the entry (e.g. from `source_file` path under `1-Projects/<project_id>/` or from payload). Scan `Ingest/Decisions/Roadmap-Decisions/` for a note with **wrapper_type: roadmap-next-step** (or roadmap-decision), same project (project_id in wrapper frontmatter or original_path points at this project's Roadmap/state), **approved: true**, and not **processed: true** / **used_at**. If found: Resolve **approved_option** (A–G, 0) to **params.action** per [User-Questions-and-Options-Reference](3-Resources/Second-Brain/User-Questions-and-Options-Reference.md) §4 (A = deepen, B = recal, C = advance-phase, D = raise cap and continue, E = revert-phase, F = sync-outputs then deepen, 0 = re-wrap) and merge into the entry's **params**. Set wrapper **processed: true**, **used_at**; move wrapper to `4-Archives/Ingest-Decisions/Roadmap-Decisions/` (ensure_structure, per-change snapshot, move with dry_run then commit). Then dispatch to auto-roadmap with the merged params so it runs "branch by action" (no smart dispatch). See Cursor-Skill-Pipelines-Reference § Apply-from-wrapper (roadmap-next-step).
  - **RESUME-ROADMAP context-tracking (pre-dispatch, mandatory):** When the entry **mode** is **RESUME_ROADMAP** (after any roadmap mode normalization) and merged **params.action** is **"deepen"** or missing or **"auto"** (so a deepen run may execute), if merged params do **not** have **`enable_context_tracking === false`** (i.e. no explicit opt-out on this entry), set **`params.enable_context_tracking = true`** before invoking auto-roadmap. This enforces default-on at dispatch so the effective flag is explicit and cannot be dropped.
  - **RESUME-ROADMAP bootstrap (run ROADMAP MODE first when state missing):** When the entry **mode** is **RESUME-ROADMAP** (after roadmap mode normalization), **before** matching to pipeline: (1) Resolve **project_id** for this entry (from `params.project_id` or from `source_file` path under `1-Projects/<project_id>/`). (2) Check whether the project **has roadmap state**: path `1-Projects/<project_id>/Roadmap/roadmap-state.md` exists (e.g. via `obsidian_read_note` or equivalent note-exists check). If it exists and parses, treat as "state present" and skip to Match mode to pipeline. (3) **If state is missing:** Scan the **current run's queue** (the in-memory list of entries being processed this EAT-QUEUE pass, in sorted order) for an entry that has **mode** exactly **`"ROADMAP MODE"`** (literal; not normalized) and the **same project_id** (from that entry's `params.project_id` or `source_file` under `1-Projects/<project_id>/`). (4) **If such a ROADMAP MODE entry exists:** If that entry's **id** is **not** in **processed_success_ids** (i.e. it has not been successfully run yet in this pass), **dispatch that ROADMAP MODE entry now**: run the ROADMAP MODE pipeline (auto-roadmap setup: Phase 0 + roadmap-generate-from-outline) with that entry's payload (project_id, source_file, params). **On success:** append Watcher-Result for that entry's **id**, add that **id** to **processed_success_ids** so Step 8 will clear it, then proceed to dispatch the current RESUME-ROADMAP entry as usual (do **not** drop RESUME-ROADMAP). **On failure:** do **not** run RESUME-ROADMAP; append failure to Watcher-Result for the ROADMAP MODE entry's id, append failure for the current entry (e.g. `message: "RESUME-ROADMAP skipped: ROADMAP MODE setup failed for project <project_id>"`), and continue to the next queue entry. If the ROADMAP MODE entry was already run in this pass (its id is in processed_success_ids), proceed to dispatch RESUME-ROADMAP as usual. (5) **If no ROADMAP MODE entry for this project exists in the queue:** Keep current behavior — dispatch RESUME-ROADMAP; when auto-roadmap (or roadmap-deepen) finds no state, it will error and create the Decision wrapper / Errors.md entry as today.
- **Match mode to pipeline**:
  - `INGEST MODE` → full-autonomous-ingest (always-ingest-bootstrap + para-zettel-autopilot). For entries whose `source_file` is an `Ingest/*.md` note (and no `hard_target_path` yet), this runs **Phase 1 (propose-only + Decision Wrapper, no moves/renames)**. For entries whose `source_file` is a Decision Wrapper under `Ingest/Decisions/` and/or where `feedback-incorporate` emits a `hard_target_path`, the ingest run is treated as **Phase 2 apply-mode** and may execute `obsidian_move_note` / `obsidian_rename_note` after snapshots and confidence checks.
  - **`FORCE-WRAPPER`** → Run the pipeline **inferred from `source_file`** with **force_wrapper: true** so the pipeline creates a Decision Wrapper instead of performing the destructive step (move, rename, structural distill, etc.). Infer pipeline as: `source_file` under `Ingest/` → full-autonomous-ingest; under `1-Projects/`, `2-Areas/`, or `3-Resources/` → autonomous-organize; optionally same for DISTILL/EXPRESS/ARCHIVE when scope is clear. Pass force_wrapper in context (e.g. queue payload or agent-visible flag) so the pipeline rule creates a wrapper in the appropriate subfolder (e.g. `Ingest/Decisions/Ingest-Decisions/` or `Refinements/` with `wrapper_type: force-wrapper`) and skips the destructive action. Apply when user approves wrapper is handled by Step 0 (same as other wrapper types).
  - `ORGANIZE MODE` → autonomous-organize (auto-organize).
  - `DISTILL MODE` → autonomous-distill (auto-distill).
  - `EXPRESS MODE` → autonomous-express (auto-express).
  - **`SCOPING MODE`** / **`SCOPING`** → queue alias: run **DISTILL MODE** then **EXPRESS MODE** on the **same note** (resolve `source_file` as PMG path; if missing, use payload or skip). No new pipeline; process as two steps in sequence (autonomous-distill on path, then autonomous-express on path; research-scope runs inside express). Optional second argument: `SCOPING MODE <path-to-pmg>` in prompt or source_file. Append one Watcher-Result line per queue entry after both steps complete.
  - `ARCHIVE MODE` → autonomous-archive (auto-archive).
  - **NORMALIZE-MASTER-GOAL** → Run **normalize-master-goal** skill on `source_file`: backup + per-change snapshot, then restructure the note body to [[Templates/Master-Goal]] (One-line, Vision, Phases, Technical Integration, TL;DR, Related). Skip if note is not a PMG (is_master_goal or path matches *Master*Goal*). Append Watcher-Result line.
  - **ROADMAP MODE** → Run **auto-roadmap** setup path (Phase 0 + workflow_state + roadmap-generate-from-outline): resolve project_id and source_file from payload; run ROADMAP MODE behavior per auto-roadmap rule (create Phase 0 artifacts if missing, run roadmap-generate-from-outline). Do **not** append RESUME-ROADMAP after setup; the first resume is crafted by the user. Same behavior as "ROADMAP MODE – generate from outline". When seed is a PMG, normalize-master-goal runs internally before parsing. Append Watcher-Result line.
  - **ROADMAP MODE – generate from outline** (when seed is a PMG) runs normalize-master-goal internally before parsing; this queue mode allows on-demand normalization without generating a roadmap. Treat as **ROADMAP MODE** (same dispatch as above).
- **TASK-TO-PLAN-PROMPT** → Turn roadmap task into Cursor-ready prompt: read task from source_file + locator (params); output one concrete prompt string; append to note "Prompts" section or dedicated note; optionally create prompt-decision wrapper. Stub: use Templates/Planning-Prompt-Task.md; merge session_success_hint and git_diff_hint from params when present. Append Watcher-Result line.
  - **RESUME-ROADMAP** → Run **auto-roadmap** (single roadmap continuation path): resolve project_id from source_file or payload; **pass full params** (merged: queue entry + Config prompt_defaults.roadmap). Auto-roadmap reads **params.action** (default: deepen) and dispatches: deepen → roadmap-resume (optional) + roadmap-deepen; recal → roadmap-audit; revert-phase → roadmap-revert; sync-outputs → roadmap-phase-output-sync; handoff-audit → hand-off-audit; resume-from-last-safe → find safe phase then deepen; expand → expand-road-assist. Validate params.action in allowed enum; invalid → reject and log to Errors.md. Append Watcher-Result line.
  - **RESUME-FROM-LAST-SAFE**, **RECAL-ROAD**, **SYNC-PHASE-OUTPUTS**, **REVERT-PHASE**, **HANDOFF-AUDIT**, **EXPAND-ROAD** → Already **normalized** to RESUME-ROADMAP with params.action set (see Roadmap mode normalization above); same RESUME-ROADMAP dispatch.
  - **ROADMAP-ONE-SHOT** (deprecated) → Run **auto-roadmap** with one-shot branch: log deprecation to Ingest-Log; run classic **roadmap-generate-from-outline** (full tree, no state, no distill). Append Watcher-Result line.
  - **TASK-ROADMAP** → dispatch per Queue-Sources (roadmap task to plan prompt or similar); when implemented, run corresponding skill. (Future: ADD-ROADMAP-ITEM, etc.)
  - **RESEARCH-AGENT** → **Before** calling research-agent-run: Resolve **project_id** and **linked_phase** from `source_file` (e.g. phase note under `1-Projects/<project_id>/Roadmap/`) or from payload `project_id` + `params.phase` / `params.linked_phase`. Require **both** to be present after resolution. If either is missing, **skip** this entry; append Watcher-Result: `status: failure | message: "RESEARCH-AGENT: project_id or linked_phase missing"`; do **not** run the skill; do **not** add to processed_success_ids (so Step 8 writes this entry back with `queue_failed: true`). **When both resolved:** Run **research-agent-run** skill (vault-first → query → fetch → synthesize; write to `Ingest/Agent-Research/`). For each new note path created, append one **INGEST MODE** entry to the queue (or in-memory for this run) with `source_file: "<path>"`. If `params.research_distill === true`, also append **DISTILL MODE** for each new research note. **After** research-agent-run returns: if it returns **0 new note paths** (empty run), treat as **failure** for this entry: append Watcher-Result with `status: failure` and message e.g. "RESEARCH-AGENT: 0 notes (empty or failed research)"; do **not** add to processed_success_ids. Append Watcher-Result line(s).
  - **AUDIT-CONTEXT** → Run **context-vs-pipeline-audit** skill: resolve `source_file` or `project_id` from payload; read workflow_state, Distill-Log, Express-Log; compute overlap; write to Audit-Context-Focus.md. Append Watcher-Result line.
  - **SEEDED-ENHANCE** → run highlight-seed-enhance on `source_file` (note with user `<mark>`); backup + snapshot before edits; see mobile-seed-detect rule and highlight-seed-enhance skill.
  - **BATCH-DISTILL** → run autonomous-distill on each note in scope (vault or folder); use batch snapshot when batch size > batch_size_for_snapshot; scope in payload.
  - **BATCH-EXPRESS** → run autonomous-express on each note in scope; batch snapshot when applicable.
  - **ASYNC-LOOP** → re-process note(s) after async preview (user set approved: true or added feedback); run feedback-incorporate then proceed to snapshot + commit if post_loop_conf ≥85%.
  - **NAME-REVIEW** → run name-enhance in batch on scope from payload (`folder` or `paths` list; if absent use default scope from config or recent notes). Optional payload: `explicit_rename_request` dict for MOC/project renames. For each note in scope: name-enhance(path, context: "name-review", explicit_rename_request); apply renames for Regular notes when confidence ≥85% (with per-change snapshot). Log each result to **Name-Review-Log.md** (or Organize-Log) with pipeline: name-review, suggested_name, applied, protection_triggered, old_stem. Append one line per processed queue entry to Watcher-Result.
  - **GARDEN-REVIEW** → run **auto-garden-review** flow: call **`obsidian_garden_review`**(scope, focus, output_path, auto_apply) from queue `params` or defaults (scope: all; focus: all; auto_apply: false). Use report to feed autonomous-distill and/or autonomous-organize batches; log to Feedback-Log or Organize-Log. Append one Watcher-Result line.
  - **CURATE-CLUSTER** → run **auto-curate-cluster** flow: call **`obsidian_curate_cluster`**(query, note_list, actions) from queue `params` or `prompt`. Analyze report (gaps, merges, synthesis); optionally propose split/MOC/merge; log to Feedback-Log. Append one Watcher-Result line.

### 6. Run

- **Guidance-aware runs:** When about to run a pipeline for an entry with non-empty **`prompt`** or when the note at **`source_file`** has **`user_guidance`** or tag **`#guidance-aware`**, treat the run as **guidance-aware** (see [guidance-aware](.cursor/rules/always/guidance-aware.mdc)): run **feedback-incorporate** to load guidance (from note `user_guidance`, from entry `prompt`, from entry `agent_reasoning` as AI-only context, or from an associated Decision Wrapper under `Ingest/Decisions/`) and pass the resulting **`guidance_text`** (and any `hard_target_path` / `guidance_conf_boost` hints) into the pipeline context so that when the agent runs classify_para, subfolder-organize, name-enhance, distill_note, split_atomic, it has the guidance in context. **Merge crafted params with user_guidance**: Append user_guidance text to rationale_style if compatible (e.g. "concise + explain rankings"); when present, keep `agent_reasoning` in a clearly separated section of the merged prompt (e.g. "AI reasoning from prior C choices: …") so it is distinguishable from human guidance. Log full merged params to Prompt-Log.md for audit. Do not override or silently rewrite user_guidance with AI reasoning; inject defaults only where missing.
- **Decision Wrappers → apply-mode ingest:** For Decision Wrapper entries specifically, `feedback-incorporate` resolves `approved_option` / `approved_path` into a `hard_target_path` for the original Ingest note and emits guidance from the wrapper’s Thoughts block. The subsequent `INGEST MODE` run for that note is treated as **Phase 2 apply-mode**: Phase 1 rules (para-zettel-autopilot, always-ingest-bootstrap, ingest-processing) have already run; this run may now perform `obsidian_move_note` (dry_run then commit) and `obsidian_rename_note` when confidence and snapshot gates are satisfied. All backup/snapshot/dry_run safety from the ingest pipeline remains unchanged.
- Execute the corresponding pipeline for each entry. Backup, snapshot, and confidence rules from the pipeline reference and MCP rule apply unchanged. Process one entry fully (including logging) before starting the next.

### 7. Log

- Append one line per processed request to `3-Resources/Watcher-Result.md`:
  `requestId: <id> | status: success|failure | message: "..." | trace: "..." | completed: <ISO8601>`.

### 8. Clear passed entries only (§2e)

- **Comment-fatigue stub (post-apply):** After Step 0 and dispatch, optionally run a post-apply check: if comments-per-file (for files touched this run or scope from params) > **comment_fatigue_threshold** (from Parameters, e.g. 50), log `#review-needed` to **Feedback-Log.md** per Logs § Error Handling Protocol. Full heuristic (e.g. scan codebase for comment density) implement when needed; stub documents the contract.
- Track which requestIds were logged with `status: success` vs `status: failure` (or skipped without running a pipeline). Build the set **processed_success_ids** of `id` values for entries that completed with **status: success** this run.
- **Re-read before write (preserve pipeline appends):** Step 8 **preserves lines that were appended to the queue file during this run** (e.g. by roadmap-deepen or RESEARCH-AGENT) so that pipeline-appended follow-ups are not lost. **Before** writing the new queue content:
  1. **Re-read** `.technical/prompt-queue.jsonl` from disk (same path as step 1). If the file is missing or unreadable, treat re-read content as empty (proceed with merge from in-memory state only).
  2. **Merge logic:** For each line in the re-read file: try to parse as JSON; if parse succeeds and the entry has an `id` (or use `mode`+`source_file`+`id` as fallback key) that is in **processed_success_ids**, **omit** that line (it was processed successfully). Otherwise **keep** the line — including lines that were not in the original read (i.e. appended during the run by a pipeline).
  3. **Failed/skipped from original run:** For each entry from the **original** parsed queue (step 1) that **failed or was skipped** (not in processed_success_ids), add it to the output with **`queue_failed: true`** set on the object before writing the line. Thus the next EAT-QUEUE run will skip them (no automatic retry).
  4. **Write:** Write the kept lines from the re-read file (excluding successful entries) plus the failed/skipped entries from the original run (with `queue_failed: true`). Preserve order: kept re-read lines first (in file order), then failed/skipped from original run, then CHECK_WRAPPERS if needed.
- If **approved_wrappers_remaining** (set in step 0) is true, **append one `CHECK_WRAPPERS` entry** to the rewritten queue file, e.g. `{"mode":"INGEST MODE","prompt":"CHECK_WRAPPERS","source_file":"Ingest/Decisions/","id":"check-wrappers-<timestamp>"}`, so the next run has it for visibility; step 0 will again process any remaining approved wrappers.
- If all entries passed and approved_wrappers_remaining is false, the queue file contains only any lines that were appended during the run (or is empty if none).

## Watcher-Result contract

- When a run was triggered by EAT-QUEUE (queue or pasted EAT-CACHE), append the one-line format per processed `requestId` as above. See `[.cursor/rules/always/watcher-result-append.mdc](.cursor/rules/always/watcher-result-append.mdc)`.

## Safety

- **Step 0 always runs first**: The always-check wrappers step runs before reading the queue, so approved wrappers are processed even when the queue is empty or the `CHECK_WRAPPERS` entry was omitted.
- Do not run destructive pipelines on a note whose path is under `Ingest/` until batch INGEST has been processed in this run (ordering enforces this).
- Missing queue file or zero valid entries (after step 2) → exit without further dispatch; step 0 has already run. Missing `source_file` or unknown mode → skip entry, log failure, continue. Tagged (`queue_failed`) entries are never processed; they are only written back when they fail again.
