---
description: "Route queue and task-queue triggers to the Queue/Dispatcher subagent. Other mode triggers still map to their context rules per system-funnels."
globs: "*"
alwaysApply: true
---

# Dispatcher (always-on routing)

- **Role**: Recognize **queue-related** triggers and route them to the **Queue/Dispatcher subagent**. All other triggers (INGEST_MODE, DISTILL_MODE, EXPRESS_MODE, ARCHIVE_MODE, ORGANIZE_MODE, roadmap modes, GARDEN REVIEW, CURATE CLUSTER, etc.) continue to map to their existing context rules as documented in [system-funnels.mdc](.cursor/rules/always/system-funnels.mdc).
- **Shared core**: Every run must still apply the shared always rules: [core-guardrails.mdc](.cursor/rules/always/core-guardrails.mdc), [confidence-loops.mdc](.cursor/rules/always/confidence-loops.mdc), [guidance-aware.mdc](.cursor/rules/always/guidance-aware.mdc), [mcp-obsidian-integration.mdc](.cursor/rules/always/mcp-obsidian-integration.mdc), [watcher-result-append.mdc](.cursor/rules/always/watcher-result-append.mdc), [backbone-docs-sync.mdc](.cursor/rules/always/backbone-docs-sync.mdc). This rule does not replace them; it only adds routing for the triggers below.

## Delegation and fallback

- **Dispatch via Task subagent tool (with Task harden pass)**: For pipeline modes (ingest, roadmap, distill, express, archive, organize, research, **validator**), the queue processor **never calls the raw Task tool directly**. Instead, it MUST invoke the **Task harden pass** described in [[3-Resources/Second-Brain/Subagent-Safety-Contract|Subagent-Safety-Contract]] § **Task harden pass (capability probing, profiles, and launch modes)**:
  - Pass **prompt** = the full hand-off block (per Subagent-Safety-Contract) and **desired_subagent_type** = the pipeline type (roadmap | ingest | distill | express | archive | organize | research | validator), along with the current **task_role** (e.g. `layer1_queue`) and **effective_pipeline_mode** / profile snapshot from Config. **Layer 1 only:** after prompt-queue **A.7**, **queue.mdc A.7a** runs **`python3 -m scripts.eat_queue_core.harness post_queue_gitforge`** when **`gitforge.harness_enabled`** is **true** (default) and mode is **`balance`** or **`quality`** (**`speed`** skips GitForge; post-run git/export tail — not a pipeline mode entry). **Legacy:** **`Task(subagent_type: "gitforge")`** only when **`gitforge.harness_enabled`** is **false**.
  - The harden pass:
    - Uses the **per-run capability cache** (`available_subagents` / `raw_errors`) to decide whether this `subagent_type` is actually supported by the host.
    - Applies the **profile-specific helper graph** (fast | balance | extreme) to decide whether this helper is **mandatory** or **out of graph** for this run.
    - Normalizes the launch decision:
      - `launch_mode: native_subagent` when `available_subagents[type] === true`.
      - `launch_mode: generalPurpose_fallback` only for non-mandatory helpers when explicitly configured.
      - Or marks the step as **blocked** (no Task call) when a **mandatory** helper is unavailable, so the parent MUST NOT report full Success.
  - When the harden pass elects to launch, it calls the Cursor `Task` tool on behalf of this rule with the chosen `subagent_type` and a decorated prompt that includes:
    - `task_harden_metadata.layer_role: layer1_queue`,
    - `task_harden_metadata.launch_mode: native_subagent | generalPurpose_fallback`,
    - `task_harden_metadata.expected_contract` identifying the contract (e.g. `roadmap_handoff_auto`, `archive_candidate`, etc.).
  - For **ROADMAP_HANDOFF_VALIDATE**, the queue passes **model** from Config § validator.roadmap_handoff.model into the harden pass so the underlying `Task(validator)` call uses the fixed model when it is actually reachable.
  - The subagent still runs in a separate context with only that prompt; the queue processor waits for the Task call to return, inspects the child’s `task_harden_result` footer (`task_launch_mode`, `contract_satisfied`) when present, logs Watcher-Result, and continues. When `contract_satisfied: false` on a **mandatory** contract under the active profile, Layer 1 MUST NOT treat the entry as fully successful even if the subagent text claims “Success”.
  - Pipeline subagents may in turn call only the three sanctioned **nested helper** subagents defined in the Subagent-Safety-Contract — **Internal Repair Agent (IRA)**, **Validator**, and **Research** — and must route those nested calls through the **same Task harden pass** (task_role `helper_internal_repair_agent` / `helper_validator` / `helper_research`) instead of using raw Task.
  - **PromptCraftSubagent** is **not** a nested pipeline helper: **only Layer 0 (manual)** or **Layer 1 ([[.cursor/rules/agents/queue.mdc|queue.mdc]] A.5d)** may call **`Task(prompt_craft)`** (again via the Task harden pass with `desired_subagent_type: "prompt_craft"`); IRA and Validator must **never** call it.
  - **GitForge** is **not** a nested pipeline helper: **only Layer 1** after **queue.mdc A.7a** may run **`post_queue_gitforge`** (default) or **`Task(gitforge)`** (legacy when **`gitforge.harness_enabled`** is **false**); IRA, Validator, Layer 0, and Layer 2 pipelines must **never** invoke either path.
  - **GitForge tail** after **A.7a**: on harness non-zero exit or legacy **`Task(gitforge)`** failure, **Proof-on-failure** ([[3-Resources/Second-Brain/Subagent-Safety-Contract|Subagent-Safety-Contract]] § Proof-on-failure); GitForge failure MUST NOT roll back queue consumption.
- **Task `model` (Cursor API):** **Omit** `model` on Task calls to use the parent chat's model (inherit behavior). Use **`model: "fast"`** only when intentionally selecting the fast tier. **Never** pass `model: "inherit"` — invalid and fails validation. Validator (and similar) dispatches pass Config `model` as documented. Agent files `.cursor/agents/*.md` may use YAML `model: inherit`; that is **not** a Task payload value. See [Subagent-Safety-Contract](3-Resources/Second-Brain/Subagent-Safety-Contract.md) § Cursor Task tool: `model` parameter.
- **All pipeline dispatch via subagent**: All pipeline-mode entries **must** be routed through the **Task** subagent tool (launch explicit subagent). There is **no same-run fallback**. If a Task call **fails**, do **not** run the pipeline inline. For that entry: append a failure line to Watcher-Result (requestId, status: failure, message e.g. "subagent launch required; Task subagent call failed"), log to Errors.md per Error Handling Protocol, do not add the entry to processed_success_ids (so it remains in the queue or is marked queue_failed at rewrite), and continue to the next entry.
- **Watcher-Result**: If the agent cannot write to `3-Resources/Watcher-Result.md` (permission or sandbox), it logs the intended line to `3-Resources/Errors.md` (Watcher-Result fallback) and continues; queue completion is not blocked.
- **Rollback / legacy mode:** Production no longer supports inline pipeline execution. To disable native subagents while keeping legacy rules for reference, rename or remove `.cursor/agents/*.md`; pipeline dispatch still requires the **Task** subagent tool (no same-run fallback). Deprecated fallback behavior is documented in [[4-Archives/Resources/Second-Brain-Deprecated/Queue-Same-Run-Fallback-2026-03-17]].

## Queue triggers → spawn Layer 1 (Queue subagent) via Task

When the user instruction contains any of these (case-insensitive):

- **EAT-QUEUE** *(canonical)* — includes **EAT-QUEUE BREAK-SPIN** (same queue pass; see **BREAK-SPIN** below)
- **Process queue**
- **EAT-CACHE** / **eat cache**
- **PROCESS TASK QUEUE**

then **Layer 0 (this agent) must NOT run queue logic**. Your **only** action is to **launch the Queue/Dispatcher subagent (Layer 1)** by **calling the `Task` tool once**. Per [[3-Resources/Second-Brain/Subagent-Safety-Contract|Subagent-Safety-Contract]] § Task-`attempt-before-skip`, you **must attempt** this Task call with `subagent_type: "queue"` rather than inferring from schema that it is unavailable; treat only real Task errors as unavailability.

1. **Build a hand-off** for the Queue subagent that includes:
   - Vault root (workspace path).
   - **Prompt queue path (summary line):** Legacy default **`.technical/prompt-queue.jsonl`**. When **parallel dual-track** is active (see below), the effective file is under **`.technical/parallel/<track>/prompt-queue.jsonl`** — Layer 1 resolves **PQ** per [[.cursor/rules/agents/queue.mdc|queue.mdc]] **A.0x**.
   - Task queue path: `3-Resources/Task-Queue.md`.
   - Which to process: prompt queue (EAT-QUEUE / Process queue / EAT-CACHE) or task queue (PROCESS TASK QUEUE) or both if the user asked for both.
   - **Queue lane (prompt-queue flows only):** When the instruction contains a **prompt-queue** trigger (**EAT-QUEUE**, **Process queue**, **EAT-CACHE** / **eat cache**, case-insensitive) **and** matches **`lane`** + a lane token (regex: **`(?i)\blane\s+([a-z0-9_-]+)\b`**), set **`queue_lane_filter`** = token **lowercased**. Validate against Second-Brain-Config **`queue.allowed_lanes`** (default if missing: `default`, `shared`, `sandbox`, `godot`, `core`). If invalid: **do not** call **`Task(queue)`**; append **Errors.md** (`error_type: queue_lane_filter_invalid`) and a **Watcher-Result** **failure** line with message prefix **`queue_lane_filter_invalid`**; stop. If valid, include in the hand-off a line **`## queue_lane_filter`** followed by the token (or equivalent YAML block). Supported UX: **`EAT-QUEUE lane sandbox`**, **`EAT-QUEUE lane godot`**, **`EAT-QUEUE lane shared`**, **`EAT-QUEUE lane default`**, and the same with **Process queue** / **EAT-CACHE**. Omit **`## queue_lane_filter`** when no lane token — Layer 1 processes **all** entries. **PROCESS TASK QUEUE** alone: ignore **`lane`** unless the user also triggered a prompt-queue pass.
   - **`## parallel_context` (minimal; prompt-queue only):** When **`parallel_execution.enabled`** is **true** in Second-Brain-Config and **`default_to_legacy`** is not **true**, and **`queue_lane_filter`** matches a **`parallel_execution.tracks[].lane`**, append a fenced **`yaml`** block under **`## parallel_context`** with: **`parallel_track`** (track **`id`**), **`technical_bundle_root`**: `.technical/` + that track’s **`technical_subdir`**, **`resolved_prompt_queue_path`**, **`resolved_eat_queue_run_plan_path`**, **`resolved_queue_continuation_path`**, **`resolved_prompt_queue_audit_path`**, **`resolved_tmp_prompt_path`** (each = **`technical_bundle_root`** + `/` + filename: `prompt-queue.jsonl`, `eat_queue_run_plan.json`, `queue-continuation.jsonl`, `prompt-queue-audit.jsonl`, `tmp-prompt.json`), **`parallel_branch_prefix`**, **`parallel_export_path`** from that track row, and when the track row defines **`lane_project_id`**: **`lane_project_id`**, **`lane_project_root`**: `1-Projects/<lane_project_id>/` (or explicit **`lane_project_root`** from Config), **`roadmap_dir`**: `lane_project_root` + `Roadmap/`. **Omit** **`## parallel_context`** when parallel is disabled, legacy default, or lane does not match a configured track (Layer 1 uses **A.0x** legacy branch).
   - If EAT-CACHE with pasted payload: include the pasted payload (e.g. `queued_prompts`) in the hand-off.
   - **BREAK-SPIN (optional):** When the instruction contains **BREAK-SPIN** (with **EAT-QUEUE** / **Process queue**), include any **operator-authored** YAML from the user message in the hand-off as a dedicated section **`## operator_break_spin`** with a fenced **`yaml`** block. Minimal schema (all keys optional except intent): **`operator_break_spin: true`**, **`break_spin_target_queue_entry_id`**, **`break_spin_preferred_action`** (`deepen` \| `recal` \| …), **`break_spin_pivot_to_track`**, **`break_spin_rationale`**, **`break_spin_circled_locus`**. Layer 1 merges this into **`layer1_resolver_hints`** / roadmap hand-off per [[.cursor/rules/agents/queue.mdc|queue.mdc]] (alternate deepen first; **recal** only as fallback when no alternates or operator override — not the default “break” from spin).
   - Instruction: "You are the Queue/Dispatcher subagent (Layer 1). Process the queue(s) as specified in .cursor/rules/agents/queue.mdc: Step 0 (wrappers), read, parse/validate/dedup/order, then for each pipeline entry call the Task tool to launch that pipeline's subagent, Watcher-Result, rewrite. Do not run queue logic in the parent context; you run in this context only."
2. **Task hand-off comms (Layer 0→1):** When Second-Brain-Config **`task_handoff_comms.enabled`** is not **false**, **before** **`Task`**: read-append-write **`task-handoff-comms.jsonl`** with **`handoff_out`** per [[3-Resources/Second-Brain/Docs/Task-Handoff-Comms-Spec|Task-Handoff-Comms-Spec]] — default path **`.technical/task-handoff-comms.jsonl`**; when **## parallel_context** in the hand-off includes **`technical_bundle_root`**, use **`{technical_bundle_root}/task-handoff-comms.jsonl`** so comms align with the lane’s PQ (**queue.mdc A.0x**). Fields: new **`task_correlation_id`** (UUID), **`parent_task_correlation_id`: null**, **`from_actor: layer0_chat`**, **`to_actor: layer1_queue`**, **`subagent_type: queue`**, **`queue_entry_id`**: `"-"` or synthetic id if known, **`parent_run_id`**, **`project_id`**, **`vault_root`**, **`body`** = full **`prompt`** for the Queue **`Task`** (sanitized), **`sanitization_rules_applied`**. **After** **`Task`** returns, append **`return_in`** with the same **`task_correlation_id`** and full return or sanitized error. Respect **`task_handoff_comms.max_body_bytes`**.
3. **Call the `Task` tool** with **subagent_type: `queue`** (or the type that loads `.cursor/agents/queue.md`), **description**: one sentence (e.g. "Process the prompt queue and/or task queue"), **prompt**: the full hand-off text above. Wait for the Task call to return.
3a. **Prompt-queue empty-bootstrap receipt gate (Layer 0 post-return validation):** For prompt-queue triggers (**EAT-QUEUE** / **Process queue** / **EAT-CACHE**) where Layer 0 passed a **`queue_lane_filter`**, inspect the queue subagent return text. If it reports or implies **zero considered/processed entries** (for example phrases like `Entries considered: 0`, `Entries processed: 0`, `No actionable items`) and does **not** include an explicit A.1b branch outcome token (`empty-queue bootstrap appended`, `empty_queue_bootstrap_deduped_`, `empty_queue_bootstrap_no_record`, `OPERATOR ALARM: empty queue bootstrap failed`, or `a2_still_empty_after_a1b`), treat the run as **contract-failed** at Layer 0:
   - Append **Errors.md** entry (`error_type: layer0_empty_queue_bootstrap_receipt_missing`) with the lane token and a short excerpt of the queue return.
   - Append **Watcher-Result** failure line with message prefix **`layer0_empty_queue_bootstrap_receipt_missing`**.
   - Do **not** present this run as clean success; instruct operator to re-run after queue/dispatcher repair.
4. **Do not** read the prompt queue or Task-Queue yourself; **do not** run queue logic in this context. **Narrow exception:** ensuring **`dirname(PQ)`** exists and creating an **empty** **PQ** file when missing (per **[[.cursor/skills/queue-bootstrap-guard/SKILL.md|queue-bootstrap-guard]]**) is **not** a queue read or parse — Layer 0 must still not **parse** lines or **dispatch** entries before **`Task(queue)`**. If `Task(subagent_type: "queue")` fails or cannot run, follow **[[3-Resources/Second-Brain/Subagent-Safety-Contract|Subagent-Safety-Contract]] § Proof-on-failure** (comms `return_in` when enabled + Errors.md + correct `fallback_reason`). When **parallel_context** / lane resolves a per-track **PQ**, use that track’s **`technical_bundle_root`** for **task-handoff-comms.jsonl** as in step 2.
5. **Layer 0 loud wrap (optional; after `Task(queue)` returns only):** When Second-Brain-Config **`queue.layer0_escalation_enabled`** is **true**, parse the Queue subagent **return** text for a fenced **`yaml`** block under **`## layer0_queue_signals`** (see [[.cursor/agents/queue.md|agents/queue.md]]). If **`no_gain_terminal`** or **`break_spin_zero_alternates`** is **true**, prepend **one or more** lines from **`queue.layer0_no_gain_voice_lines`** (or the vault path **`queue.layer0_no_gain_voice_vault_path`** when set) to **your user-visible reply** — blunt / attention-grabbing copy is allowed **here only**. **Do not** put loud copy in **`3-Resources/Watcher-Result.md`** `message` or in subagent returns; keep Watcher lines **neutral and parse-safe** per [[.cursor/rules/always/watcher-result-append.mdc|watcher-result-append]].

## PromptCraft triggers (Layer 0 — not EAT-QUEUE)

When the user instruction contains **REPAIR CRAFT** or **PROMPT CRAFT RECOVERY** (case-insensitive), **Layer 0** does **not** run queue logic. **Layer 0** builds a hand-off from the user message (paste **`prompt_craft_request`** YAML if supplied, or describe failure context) and **calls the `Task` tool** once with **subagent_type `prompt_craft`** (or **generalPurpose** + PromptCraft preamble if the host enum lacks `prompt_craft`). **Layer 0 does not append** the prompt queue (**PQ**); the operator or a subsequent EAT-QUEUE / Layer 1 step applies lines. On `Task(prompt_craft)` failure: **Proof-on-failure** (Subagent-Safety-Contract § Proof-on-failure). See [[3-Resources/Second-Brain/Docs/Prompt-Craft-Subagent|Prompt-Craft-Subagent]]. When **`task_handoff_comms.enabled`** is not **false**, wrap that **`Task`** with **`handoff_out` / `return_in`** appends to **`.technical/task-handoff-comms.jsonl`** per [[3-Resources/Second-Brain/Docs/Task-Handoff-Comms-Spec|Task-Handoff-Comms-Spec]] (**`from_actor: layer0_chat`**, **`parent_task_correlation_id`: null**, fresh **`task_correlation_id`** per call).

## Other triggers

All other mode phrases (INGEST_MODE, DISTILL_MODE, EXPRESS_MODE, ARCHIVE_MODE, ORGANIZE_MODE, ROADMAP_MODE, RESUME_ROADMAP, GARDEN REVIEW, CURATE CLUSTER, etc.) are **not** handled by this dispatcher; they continue to be routed per [system-funnels.mdc](.cursor/rules/always/system-funnels.mdc). For pipeline modes (ingest, distill, express, archive, organize, roadmap, research, validator): queue processor **calls the Task tool** with hand-off as prompt and matching subagent_type (validator for ROADMAP_HANDOFF_VALIDATE; model from config when applicable). Direct triggers (user said "Resume roadmap" etc. without EAT-QUEUE): launch via **Task** + hand-off; on failure, **Proof-on-failure** as in Subagent-Safety-Contract (same Errors.md / comms rules). *(Deprecated same-run fallback archived: [[4-Archives/Resources/Second-Brain-Deprecated/Queue-Same-Run-Fallback-2026-03-17]].)*
